<?xml version="1.0" encoding="utf-8" ?>
<Project>

	<PropertyGroup>
		<_UDAPI_TaskFolder>$(MSBuildThisFileDirectory)..\tasks\netstandard2.0</_UDAPI_TaskFolder>
		<_UDAPI_TaskAssembly_>$(_UDAPI_TaskFolder)\Skyline.DataMiner.SDM.UserDefinedApi.Build.dll</_UDAPI_TaskAssembly_>
	</PropertyGroup>

	<!--Register Tasks -->
	<UsingTask TaskName="Skyline.DataMiner.SDM.UserDefinedApi.OpenApiTask" AssemblyFile="$(_UDAPI_TaskAssembly_)"/>
	<UsingTask TaskName="Skyline.DataMiner.SDM.UserDefinedApi.PackageTask" AssemblyFile="$(_UDAPI_TaskAssembly_)"/>

	<!-- Default values, this can be overridden-->
	<PropertyGroup>
		<OpenApiFormat Condition="'$(OpenApiFormat)' == ''">yaml</OpenApiFormat>
		<GenerateOpenApi Condition="'$(GenerateOpenApi)' == ''">false</GenerateOpenApi>
		<GenerateUDAPIPackage Condition="'$(GenerateUDAPIPackage)' == ''">false</GenerateUDAPIPackage>
	</PropertyGroup>
</Project>