<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<!-- =================================================================== -->
	<!--  OPENAPI GENERATION                                                 -->
	<!-- =================================================================== -->
	<Target Name="Generate OpenApi Specification"
			Condition=" '$(GenerateOpenApi)' == 'true' "
			Inputs="@(Compile)"
			Outputs="$(OutputPath)openapi/openapi.$(OpenApiFormat)">

		<Message Text="Running OpenApiTask from Skyline.DataMiner.SDM.UserDefinedApi"
     Importance="High" />

		<OpenApiTask
			ProjectDirectory="$(MSBuildProjectDirectory)"
			OutputPath="$(OutputPath)openapi"
			ProjectName="$(MSBuildProjectName)"
			ProjectVersion="$(Version)"
			SourceFiles="@(Compile)"
			References="@(ReferencePath)"
			Format="$(OpenApiFormat)">
		</OpenApiTask>
	</Target>

	<Target Name="Clean OpenApi Specifiation" AfterTargets="Clean">
		<RemoveDir Directories="$(OutputPath)openapi" />
	</Target>

	<!-- =================================================================== -->
	<!--  MAIN EXECUTION HOOK                                                -->
	<!-- =================================================================== -->

	<!-- This single hook ensures correct ordering:
       * First tries OpenAPI (may be skipped)
       * Then UDAPI (may be skipped)
       * Runs after the project successfully compiles -->
	<Target Name="Run UDAPI Process"
			AfterTargets="CoreCompile"
			DependsOnTargets="Generate OpenApi Specification" />

</Project>
